
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const ACTIVATE_MESSAGE_CACHE = 'ACTIVATE_MESSAGE_CACHE';
export const DROP_MESSAGE_CACHE = 'DROP_MESSAGE_CACHE';
export const STOP_PENDING_OPERATION = 'STOP_PENDING_OPERATION';
export const START_PENDING_OPERATION = 'START_PENDING_OPERATION';
